FROM amazonlinux:1
RUN yum install -y shadow-utils util-linux sudo sl
RUN groupadd -g 500 ec2-user
RUN useradd -u 500 -g 500 -G wheel ec2-user
RUN echo " %wheel    ALL=(ALL)    NOPASSWD: ALL" > /etc/sudoers
